CREATE DATABASE TEMP4;
USE TEMP4;
CREATE TABLE STUDENT (
ID INT PRIMARY KEY,
NAME VARCHAR(50),
AGE INT NOT NULL
);
INSERT INTO STUDENT VALUES(1,"KHUSHI",18),(2,"ARNAV",5),(3,"SAPNA",29),(4,"PRAVEEN",27);
SELECT * FROM STUDENT;
CREATE DATABASE XYZ;
DROP DATABASE XYZ;
SHOW DATABASES;
SHOW TABLES;
SELECT * FROM STUDENT
ORDER BY NAME ASC;
INSERT INTO STUDENT VALUES (5,"VEER",1);
CREATE DATABASE XYZ;
USE XYZ;
CREATE TABLE EMPLOYEE (
ID INT PRIMARY KEY,
NAME VARCHAR(50),
SALARY INT);
INSERT INTO EMPLOYEE VALUES(1,"ADAM",25000),(2,"BOB",300000),(3,"CASEY",40000);
SELECT * FROM EMPLOYEE;
CREATE TABLE EMP (
ID INT,
SALARY INT DEFAULT 25000);
INSERT INTO EMP(ID) VALUES(12),(56);

CREATE DATABASE COLLEGE1;
USE COLLEGE1;
CREATE TABLE STUDENTS (
ROLL INT PRIMARY KEY,
NAME VARCHAR(59),
MARKS INT NOT NULL,
GRADE VARCHAR(1),
CITY VARCHAR(20)
);
INSERT INTO STUDENTS 
(ROLL,NAME,MARKS,GRADE,CITY)
VALUES
(101,"KHUSHI",99,"A","DELHI"),
(102,"SHIV",88,"C","MUMBAI"),
(103,"RAM",67,"A","DELHI"),
(104,"OM",87,"B","PUNE");

SELECT * FROM STUDENTS;
SELECT NAME, MARKS FROM STUDENTS;
SELECT DISTINCT CITY FROM STUDENTS;
SELECT DISTINCT GRADE FROM STUDENTS;
SELECT * FROM STUDENTS WHERE CITY="MUMBAI";
SELECT * FROM STUDENTS WHERE CITY="DELHI";
SELECT * FROM STUDENTS WHERE MARKS>=80;
SELECT * FROM STUDENTS WHERE MARKS>=65 AND CITY="DELHI";

SELECT * FROM STUDENTS LIMIT 2;
SELECT * FROM STUDENTS ORDER BY MARKS ASC;
SELECT MAX(MARKS) FROM STUDENTS;
SELECT MIN(MARKS) FROM STUDENTS;
SELECT COUNT(NAME) FROM STUDENTS;
SELECT CITY,MAX(MARKS)
FROM STUDENTS #GROUP CLAUSE
GROUP BY CITY;
SELECT CITY,COUNT(ROLL)
FROM STUDENTS
GROUP BY CITY;
SELECT CITY,avg(MARKS)
FROM STUDENTS
GROUP BY CITY
ORDER BY AVG(MARKS) ASC;
SELECT GRADE,COUNT(NAME)
FROM STUDENTS
GROUP BY GRADE
ORDER BY COUNT(NAME) ASC;
#HAVING CLAUSE
SELECT CITY,COUNT(ROLL)
FROM STUDENTS
GROUP BY CITY
HAVING MAX(MARKS)>90;

(101,"KHUSHI",99,"A","DELHI"),
(102,"SHIV",88,"C","MUMBAI"),
(103,"RAM",67,"A","DELHI"),
(104,"OM",87,"B","PUNE");
SELECT NAME,COUNT(CITY)
FROM STUDENTS
WHERE MARKS>87
GROUP BY NAME
HAVING MAX(GRADE)="A";
#UPDATE
SET SQL_SAFE_UPDATES=0;
UPDATE STUDENTS
SET GRADE="O"
WHERE GRADE="A";
SELECT * FROM STUDENTS
UPDATE STUDENTS
SET MARKS=95
WHERE ROLL=103;
SELECT * FROM STUDENTS
UPDATE STUDENTS
SET GRADE="B"
WHERE MARKS BETWEEN 80 AND 90;
SELECT * FROM STUDENTS
UPDATE STUDENTS
SET MARKS=MARKS+1;
SELECT * FROM STUDENTS
UPDATE STUDENTS
SET MARKS=10,GRADE="F"
WHERE ROLL=104;
SELECT * FROM STUDENTS
#DELETE
DELETE FROM STUDENTS
WHERE MARKS<=30
SELECT * FROM STUDENTS
#FORIGN KEY
CREATE TABLE DEP(
ID INT PRIMARY KEY,
NAME VARCHAR(50)
);
INSERT INTO DEP
VALUES
(101,"ENG"),
(203,"DSA");
SELECT * FROM DEP;
UPDATE DEP
SET ID=301
WHERE ID= 203;
SELECT * FROM DEP;
CREATE TABLE TEACHERS(
ID INT PRIMARY KEY,
NAME VARCHAR(50),
DEPT_ID INT,foreign key(DEPT_ID) references DEP(ID)
ON UPDATE CASCADE
ON DELETE CASCADE
);
SELECT * FROM TEACHERS;
INSERT INTO TEACHERS
VALUES
(1,"RR",203),
(2,"ABN",101);
SELECT * FROM TEACHERS;
ALTER TABLE STUDENTS
ADD YEAR INT NOT NULL DEFAULT 20 ;

SELECT * FROM STUDENTS;
ALTER TABLE STUDENTS
DROP AGE  ;
SELECT * FROM ROLL_NO;
ALTER TABLE ROLL_NO
RENAME TO STUDENTS;
ALTER TABLE STUDENTS
CHANGE COLUMN ROLL ROLL_NO INT ;
101,"KHUSHI",99,"A","DELHI"),
(102,"SHIV",88,"C","MUMBAI"),
(103,"RAM",67,"A","DELHI"),
(104,"OM",87,"B","PUNE");
ALTER TABLE STUDENTS
CHANGE NAME FULL_NAME VARCHAR(50);
SELECT * FROM STUDENTS;
DELETE FROM STUDENTS
WHERE MARKS<90;
ALTER TABLE STUDENTS
DROP YEAR;
CREATE TABLE STU(
ID INT PRIMARY KEY,
NAME VARCHAR(50));
INSERT INTO STU
VALUES
 (1,"K"),(2,"S"),(3,"P");
 CREATE TABLE CO(
ID INT PRIMARY KEY,
COURSE VARCHAR(50));
INSERT INTO CO
VALUES
 (1,"ENG"),(2,"MATH"),(4,"PHYSICS");
 SELECT * FROM CO;
SELECT * FROM STU 
INNER JOIN CO
ON STU.ID=CO.ID;
SELECT * FROM STU
LEFT JOIN CO
ON STU.ID=CO.ID;
SELECT * FROM STU
RIGHT JOIN CO
ON STU.ID=CO.ID;
SELECT * FROM STU
LEFT JOIN CO
ON STU.ID=CO.ID
UNION
SELECT * FROM STU
RIGHT JOIN CO
ON STU.ID=CO.ID;
SELECT * FROM STU
LEFT JOIN CO
ON STU.ID=CO.ID
WHERE CO.ID IS NULL
SELECT * FROM STU
RIGHT JOIN CO
ON STU.ID=CO.ID
WHERE STU.ID IS NULL;

select replace( name ,'','-') #replace space by -
from students1;
SELECT SUBSTRING(name, 1, 2) FROM students1;
select name
from students1
where name like 'k%';